baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Alexander Melander"

theme = "kayal"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.list]
  cardView = true